services:
  app-exercise:
    build: .
    ports:
      - "3000:5173"
    command: npm run dev
    volumes:
      - .:/usr/src/app
    container_name: app-exercise
    restart: unless-stopped
    network_mode: bridge
