version: "3.3"
services:
  app-exercise:
    build: .
    ports:
      - "3000:5173"
    command: npm run dev --host 0.0.0.0 --port 5173
    volumes:
      - .:/usr/src/app
    container_name: app-exercise
    restart: unless-stopped
